server:
  port: 6085
spring:
  application:
    name: service-feign
eureka:
  client:
    serviceUrl:
      #服务注册地址
      defaultZone: http://localhost:6080/eureka/
#Feign是自带断路器的，在D版本的Spring Cloud之后，它没有默认打开。需要在配置文件中配置打开它，
#打开 Feign自带断路器
feign:
  hystrix:
    enabled: true